name: fave_reads
description: A Aqueduct application for managing a list of reads.
version: 0.0.1
author: Jermaine Oppong

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  aqueduct: ^3.0.0

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
dependency_overrides:
  postgres: ^2.1.1
